version: "3.0"

services:
    igem-software:
        build: .
        ports:
            - 8080:80
        depends_on:
            - database

    database:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: IgiemCbi1
            MYSQL_DATABASE: testigem
        volumes:
            - "./bdd_data:/var/lib/mysql"

    adminer:
        image: adminer
        ports:
            - 8081:8080
        depends_on:
            - database
